# Index for Teleport audit events.
[teleport]
homePath   = $SPLUNK_DB/teleport/db
coldPath   = $SPLUNK_DB/teleport/colddb
thawedPath = $SPLUNK_DB/teleport/thaweddb
# Keep 90 days, at most 1 GB.
frozenTimePeriodInSecs = 7776000
maxTotalDataSizeMB = 1024
